### ISSUE TITLE
MoCo pretrained model

### ISSUE THREAD

**Issue by cellimnet** [trislaz/wsi_mil#5]
Hello,
You have developed a nice pipeline for processing WSI. And i want to compare the effect of different encoders, which may improve the performance of your pipeline. Can you provide the MoCo pretrained model?
Thanks for your answering!

**Comment by trislaz** [comment]
Hello, 
I cannot open source the model used in the original publication because it was trained on private hospital data.
However, you can download here: https://github.com/drivendataorg/visiomel-melanoma/tree/main/3rd%20Place (download.sh) a MoCo model that I trained on the TCGA slides, and that performs as good as the in-domain one.

**Comment by cellimnet** [comment]
Thank you very much!
